"""Generate llms.txt and llms-full.txt for the site (llmstxt.org convention).

The whole point of this project is to make FERC audit findings machine-readable,
so an LLM-friendly entry point is a first-class output:

  llms.txt       a curated index — short summary + links to the JSON data and a
                 compact overview of reports and themes.
  llms-full.txt  the full structured corpus (findings + recommendations,
                 verbatim) in one file an LLM can ingest in a single fetch.

Both are regenerated by `build`; this module can also run standalone.
Links are relative to the site root (the deploy domain isn't fixed yet — making
them absolute is a BACKLOG item).
"""
from __future__ import annotations

import argparse
import json
import logging
from datetime import date
from pathlib import Path

from collections import Counter

from pipeline import config
from pipeline.models import AuditReport, PatternsSummary
from pipeline.patterns import load_reports, summarize

logger = logging.getLogger(__name__)

SOURCE = "https://www.ferc.gov/audits"

# Collections, in tab order, with their llms.txt section labels. Mirrors
# build.py COLLECTIONS (kept in sync by eye — both small and rarely change).
_COLLECTIONS: list[tuple[str, str]] = [
    ("ferc_audit", "FERC Audits"),
    ("prudence_review", "Prudence Reviews"),
    ("state_audit", "State PUC Audits"),
]


def _industry_suffix(meta: dict) -> str:
    """Render ' (53 electric, 10 oil, 7 gas identified)' from meta, or ''."""
    bi = meta.get("by_industry_identified") or {}
    parts = [f"{v} {k}" for k, v in sorted(bi.items(), key=lambda kv: -kv[1]) if k != "unknown"]
    return f" ({', '.join(parts)} identified)" if parts else ""


def _year_range(reports: list[AuditReport]) -> str:
    years = sorted({r.issued_date.year for r in reports if r.issued_date})
    if not years:
        return "n/a"
    return str(years[0]) if years[0] == years[-1] else f"{years[0]}–{years[-1]}"


def _counts(values) -> str:
    """'VA (5), TX (4), …' — a grounded Counter rendering for insight lines."""
    return ", ".join(f"{k} ({v})" for k, v in Counter(values).most_common())


def _collection_insight(reports: list[AuditReport], summary: PatternsSummary) -> str:
    """One grounded, mechanical line of insight for a collection (counts + keyword
    themes only — no characterization). Surfaces what the parsed findings vs the
    listed-for-reference documents actually contain."""
    structured = [r for r in reports if r.structured]
    bits = [f"{len(reports)} document(s), {_year_range(reports)}"]
    jur = {r.jurisdiction for r in reports}
    if jur - {"FERC"}:
        bits.append(f"jurisdictions: {_counts(r.jurisdiction for r in reports)}")
    if summary.finding_count:
        bits.append(
            f"{summary.finding_count} findings / {summary.recommendation_count} recommendations "
            f"parsed from {len(structured)} report(s)"
        )
    listed = len(reports) - len(structured)
    if listed:
        bits.append(f"{listed} listed for reference (orders / testimony / settlements)")
    if any(r.doc_type for r in reports if not r.structured):
        bits.append("doc types: " + _counts(r.doc_type or "—" for r in reports if not r.structured))
    if summary.themes:
        bits.append("top themes: " + ", ".join(t.theme for t in summary.themes[:4]))
    return "_" + ". ".join(bits) + "._"


def _report_line(r: AuditReport) -> str:
    """A report's index entry — findings for parsed reports, an honest
    'listed for reference' line (doc type + jurisdiction) for metadata-only docs."""
    if r.structured and r.finding_count:
        titles = "; ".join(f.title for f in r.findings if not f.is_other_matter)
        suffix = f" — findings: {titles}" if titles else ""
        fns = "/".join(r.functions) if r.functions else "n/a"
        return (
            f"- [{r.company}]({r.source_page_url}): Docket {r.docket_full or r.docket or 'n/a'}, "
            f"issued {r.issued_date or 'n/a'}, {r.audit_type or 'audit'} audit, {fns}, "
            f"{r.finding_count} finding(s){suffix}"
        )
    label = r.doc_type or "document"
    juris = f"{r.jurisdiction} · " if r.jurisdiction and r.jurisdiction != "FERC" else ""
    return (
        f"- [{r.company}]({r.source_page_url}): {juris}{label}, "
        f"Docket {r.docket or 'n/a'}, issued {r.issued_date or 'n/a'} — listed for reference"
    )


def build_index(reports: list[AuditReport], patterns: PatternsSummary, meta: dict) -> str:
    by_coll = Counter(r.collection for r in reports)
    out: list[str] = []
    out.append("# FERC Audit Explorer")
    out.append("")
    out.append(
        "> Machine-readable findings of noncompliance and staff recommendations mined from "
        "**utility audit and prudence records**, across three collections: **FERC audits** "
        "(the Office of Enforcement's financial (FA) and non-financial (PA) audits of "
        "utilities, ISOs/RTOs, and pipelines, electric/gas/oil), **FERC prudence reviews** "
        "(rate-case cost determinations), and **state PUC/PSC/SCC audits** (rate, fuel-cost, "
        "and management proceedings from several state commissions). FERC audits and the "
        "parsed state management audits are broken into findings -> recommendations (verbatim); "
        "legal orders, testimony, and settlements are listed with their source. Themes are "
        "mined by transparent keyword tagging, never LLM judgement."
    )
    out.append("")
    out.append(
        f"Scope: {meta.get('scope', 'FERC utility audits — electric, gas & oil')}, extended to "
        f"prudence reviews and state audits. As of {meta.get('generated_at')}, the corpus holds "
        f"{len(reports)} structured records: {by_coll.get('ferc_audit', 0)} FERC audits "
        f"(of {meta.get('reports_total_listed')} listed at {SOURCE}{_industry_suffix(meta)}), "
        f"{by_coll.get('prudence_review', 0)} prudence reviews, and {by_coll.get('state_audit', 0)} "
        "state PUC audits. Findings and recommendations are quoted verbatim. Independent "
        "public-interest tool, not affiliated with FERC. Links below are relative to the site root."
    )
    out.append("")
    out.append("## Data (machine-readable)")
    out.append("- [Reports](data/reports.json): every structured record with findings, recommendations, and themes")
    out.append("- [Patterns](data/patterns.json): cross-report themes with counts by industry and year")
    out.append("- [Patterns by collection](data/patterns_by_collection.json): the same aggregates, per collection/tab")
    out.append("- [Meta](data/meta.json): corpus counts and provenance")
    out.append("- [Full corpus text](llms-full.txt): all findings, recommendations, and source notes in one file (verbatim)")
    out.append("")
    for key, label in _COLLECTIONS:
        rs = [r for r in reports if r.collection == key]
        if not rs:
            continue
        out.append(f"## {label}")
        out.append(_collection_insight(rs, summarize(rs)))
        out.append("")
        out.extend(_report_line(r) for r in rs)
        out.append("")
    out.append("## Common themes (from parsed findings)")
    for t in patterns.themes:
        desc = f" — {t.description}" if t.description else ""
        out.append(f"- {t.theme}{desc} ({t.report_count} report(s), {t.finding_count} finding(s))")
    out.append("")
    out.append("## Optional")
    out.append("- [Human-readable explorer](index.html)")
    out.append(f"- [FERC audit reports (primary source)]({SOURCE})")
    out.append("")
    return "\n".join(out)


def build_full(reports: list[AuditReport], patterns: PatternsSummary, meta: dict) -> str:
    total_f = sum(r.finding_count for r in reports)
    total_r = sum(len(f.recommendations) for r in reports for f in r.findings)
    out: list[str] = []
    out.append("# FERC Audit Explorer — full structured corpus")
    out.append("")
    out.append(
        f"> All structured records across FERC audits, FERC prudence reviews, and state PUC "
        f"audits: findings (verbatim) plus staff recommendations, with a provenance note for "
        f"documents listed for reference. {len(reports)} records, {total_f} findings, "
        f"{total_r} recommendations. Generated {meta.get('generated_at')}."
    )
    out.append("")
    out.append(
        f"Primary source: {SOURCE}. Findings and recommendations are quoted verbatim; "
        "metadata-only documents (legal orders, testimony, settlements) carry their source "
        "note instead. Generated from the same data as data/reports.json."
    )
    for key, label in _COLLECTIONS:
        for r in (x for x in reports if x.collection == key):
            out.append("")
            out.append("---")
            out.append("")
            out.append(f"## {r.company}")
            forms = ", ".join(f"No. {f}" for f in r.forms) or "n/a"
            out.append(f"- Collection: {label} | Source: {r.source or 'FERC'}")
            out.append(f"- Docket: {r.docket_full or r.docket or 'n/a'} | Audit type: {r.audit_type or 'n/a'}")
            out.append(f"- Issued: {r.issued_date or 'n/a'} | Industry: {r.industry or 'n/a'} | FERC Form: {forms}")
            if r.functions:
                out.append(f"- Function(s): {', '.join(r.functions)}")
            if r.audit_period:
                out.append(f"- Audit period: {r.audit_period}")
            out.append(f"- Source page: {r.source_page_url}")
            if r.structured and r.findings:
                for f in r.findings:
                    out.append("")
                    flabel = "Other matter" if f.is_other_matter else f"Finding {f.index}"
                    out.append(f"### {flabel}: {f.title}")
                    if f.summary:
                        out.append(f.summary)
                    if f.recommendations:
                        out.append("")
                        out.append("Recommendations:")
                        for rec in f.recommendations:
                            out.append(f"{rec.number}. {rec.text}")
            else:
                out.append("- Status: listed for reference (not machine-parsed into findings)")
                if r.source_note:
                    out.append("")
                    out.append(r.source_note)
    out.append("")
    return "\n".join(out)


def write_llms(out_dir: Path, reports: list[AuditReport], patterns: PatternsSummary, meta: dict) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "llms.txt").write_text(build_index(reports, patterns, meta), encoding="utf-8")
    (out_dir / "llms-full.txt").write_text(build_full(reports, patterns, meta), encoding="utf-8")


def _meta_fallback(reports: list[AuditReport]) -> dict:
    """Standalone meta when build's meta.json isn't present yet."""
    listing = json.loads(config.LISTING_PATH.read_text(encoding="utf-8")) if config.LISTING_PATH.exists() else []
    from collections import Counter

    return {
        "generated_at": date.today().isoformat(),
        "scope": "FERC utility audits — electric, gas & oil",
        "reports_total_listed": len(listing),
        "by_industry_identified": dict(Counter(r.industry or "unknown" for r in reports)),
        "reports_structured": len(reports),
    }


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    ap = argparse.ArgumentParser(description="Generate llms.txt + llms-full.txt")
    ap.add_argument("--out", type=Path, default=config.DOCS_DIR)
    args = ap.parse_args()

    reports = load_reports(config.PROCESSED_DIR)
    reports.sort(key=lambda r: (r.issued_date or date.min, r.id), reverse=True)
    patterns = summarize(reports)

    meta_path = config.SITE_DATA_DIR / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else _meta_fallback(reports)

    write_llms(args.out, reports, patterns, meta)
    logger.info("wrote %s/llms.txt and llms-full.txt (%d reports)", args.out, len(reports))


if __name__ == "__main__":
    main()
