"""Generate llms.txt and llms-full.txt for the site (llmstxt.org convention).

The whole point of this project is to make FERC audit findings machine-readable,
so an LLM-friendly entry point is a first-class output:

  llms.txt       a curated index — short summary + links to the JSON data and a
                 compact overview of reports and themes.
  llms-full.txt  the full structured corpus (findings + recommendations,
                 verbatim) in one file an LLM can ingest in a single fetch.

Both are regenerated by `build`; this module can also run standalone.
Links are relative to the site root (the deploy domain isn't fixed yet — making
them absolute is a BACKLOG item).
"""
from __future__ import annotations

import argparse
import json
import logging
from datetime import date
from pathlib import Path

from pipeline import config
from pipeline.models import AuditReport, PatternsSummary
from pipeline.patterns import load_reports, summarize

logger = logging.getLogger(__name__)

SOURCE = "https://www.ferc.gov/audits"


def _industry_suffix(meta: dict) -> str:
    """Render ' (53 electric, 10 oil, 7 gas identified)' from meta, or ''."""
    bi = meta.get("by_industry_identified") or {}
    parts = [f"{v} {k}" for k, v in sorted(bi.items(), key=lambda kv: -kv[1]) if k != "unknown"]
    return f" ({', '.join(parts)} identified)" if parts else ""


def build_index(reports: list[AuditReport], patterns: PatternsSummary, meta: dict) -> str:
    out: list[str] = []
    out.append("# FERC Audit Explorer")
    out.append("")
    out.append(
        "> Machine-readable findings of noncompliance and staff recommendations from "
        "FERC's published **utility audit reports** — electric (Form 1), gas (Form 2) and "
        "oil (Form 6) — issued by the Office of Enforcement, Division of Audits & "
        "Accounting. Covers both financial (FA) and non-financial (PA) audits of utilities, "
        "ISOs, RTOs, and pipelines. Each report is parsed into findings -> recommendations, "
        "and cross-report themes are mined."
    )
    out.append("")
    out.append(
        f"Scope: {meta.get('scope', 'FERC utility audits — electric, gas & oil')}. "
        f"As of {meta.get('generated_at')}, {meta.get('reports_structured')} reports are "
        f"structured of {meta.get('reports_total_listed')} listed{_industry_suffix(meta)}. "
        "Findings and recommendations are quoted verbatim from each report's Executive "
        f"Summary. Primary source: {SOURCE}. Independent public-interest tool, not affiliated "
        "with FERC. Links below are relative to the site root."
    )
    out.append("")
    out.append("## Data (machine-readable)")
    out.append("- [Reports](data/reports.json): every structured report with findings, recommendations, and themes")
    out.append("- [Patterns](data/patterns.json): cross-report themes with counts by industry and year")
    out.append("- [Meta](data/meta.json): corpus counts and provenance")
    out.append("- [Full corpus text](llms-full.txt): all findings and recommendations in one file (verbatim)")
    out.append("")
    out.append("## Reports")
    for r in reports:
        titles = "; ".join(f.title for f in r.findings if not f.is_other_matter)
        suffix = f" — findings: {titles}" if titles else ""
        fns = "/".join(r.functions) if r.functions else "n/a"
        out.append(
            f"- [{r.company}]({r.source_page_url}): Docket {r.docket_full or r.docket or 'n/a'}, "
            f"issued {r.issued_date or 'n/a'}, {r.audit_type or 'audit'} audit, {fns}, "
            f"{r.finding_count} finding(s){suffix}"
        )
    out.append("")
    out.append("## Common themes")
    for t in patterns.themes:
        out.append(f"- {t.theme}: {t.report_count} report(s), {t.finding_count} finding(s)")
    out.append("")
    out.append("## Optional")
    out.append("- [Human-readable explorer](index.html)")
    out.append(f"- [FERC audit reports (primary source)]({SOURCE})")
    out.append("")
    return "\n".join(out)


def build_full(reports: list[AuditReport], patterns: PatternsSummary, meta: dict) -> str:
    total_f = sum(r.finding_count for r in reports)
    total_r = sum(len(f.recommendations) for r in reports for f in r.findings)
    out: list[str] = []
    out.append("# FERC Audit Explorer — full structured corpus")
    out.append("")
    out.append(
        f"> All structured FERC utility audit reports (electric, gas & oil): findings "
        f"(verbatim) plus staff recommendations. {len(reports)} reports, {total_f} findings, "
        f"{total_r} recommendations. Generated {meta.get('generated_at')}."
    )
    out.append("")
    out.append(
        f"Primary source: {SOURCE}. Findings and recommendations are quoted verbatim from "
        "each report's Executive Summary. Generated from the same data as data/reports.json."
    )
    for r in reports:
        out.append("")
        out.append("---")
        out.append("")
        out.append(f"## {r.company}")
        forms = ", ".join(f"No. {f}" for f in r.forms) or "n/a"
        out.append(f"- Docket: {r.docket_full or r.docket or 'n/a'} | Audit type: {r.audit_type or 'n/a'}")
        out.append(f"- Issued: {r.issued_date or 'n/a'} | Industry: {r.industry or 'n/a'} | FERC Form: {forms}")
        out.append(f"- Function(s): {', '.join(r.functions) if r.functions else 'n/a'}")
        if r.audit_period:
            out.append(f"- Audit period: {r.audit_period}")
        out.append(f"- Source: {r.source_page_url}")
        for f in r.findings:
            out.append("")
            label = "Other matter" if f.is_other_matter else f"Finding {f.index}"
            out.append(f"### {label}: {f.title}")
            if f.summary:
                out.append(f.summary)
            if f.recommendations:
                out.append("")
                out.append("Recommendations:")
                for rec in f.recommendations:
                    out.append(f"{rec.number}. {rec.text}")
    out.append("")
    return "\n".join(out)


def write_llms(out_dir: Path, reports: list[AuditReport], patterns: PatternsSummary, meta: dict) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "llms.txt").write_text(build_index(reports, patterns, meta), encoding="utf-8")
    (out_dir / "llms-full.txt").write_text(build_full(reports, patterns, meta), encoding="utf-8")


def _meta_fallback(reports: list[AuditReport]) -> dict:
    """Standalone meta when build's meta.json isn't present yet."""
    listing = json.loads(config.LISTING_PATH.read_text(encoding="utf-8")) if config.LISTING_PATH.exists() else []
    from collections import Counter

    return {
        "generated_at": date.today().isoformat(),
        "scope": "FERC utility audits — electric, gas & oil",
        "reports_total_listed": len(listing),
        "by_industry_identified": dict(Counter(r.industry or "unknown" for r in reports)),
        "reports_structured": len(reports),
    }


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    ap = argparse.ArgumentParser(description="Generate llms.txt + llms-full.txt")
    ap.add_argument("--out", type=Path, default=config.DOCS_DIR)
    args = ap.parse_args()

    reports = load_reports(config.PROCESSED_DIR)
    reports.sort(key=lambda r: (r.issued_date or date.min, r.id), reverse=True)
    patterns = summarize(reports)

    meta_path = config.SITE_DATA_DIR / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else _meta_fallback(reports)

    write_llms(args.out, reports, patterns, meta)
    logger.info("wrote %s/llms.txt and llms-full.txt (%d reports)", args.out, len(reports))


if __name__ == "__main__":
    main()
